### PR TITLE
Added a new known-issues-and-workarounds.md file.

### PR DESCRIPTION
**Pull request by tforster**
The new file includes a temporary workaround for npm audit using npmrc named profiles.

### CODE REVIEW

**Comment by victorb** [comment]
This is great! Thanks a lot for the contribution and welcome to Open-Registry :)

**Comment by victorb** [comment]
And it's live! https://docs.open-registry.dev/known-issues-and-workarounds/

`mkdocs` (tool for generating the docs website) had some troubles with the code blocks inside a list, so [had to fix that](https://github.com/open-services/open-registry/commit/5f1103a6956a16ef80f2c2a9220bf02ab24234c5)

**Comment by tforster** [comment]
Sorry about that. The file I supplied was linted using
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
with
all default settings intact. I can take a closer look to see if there's
some rules configuration to better format in the future.

Troy Forster
Consulting Technology Director
M  +1 (416) 617-4921
E  troy.forster@gmail.com
W  https://www.tforster.com  <https://www.tforster.com/>


<http://www.linkedin.com/in/tforster/> <http://github.com/tforster>
<http://twitter.com/tforster> <http://instagram.com/tforster>
<http://facebook.com/troy.forster>

**Comment by victorb** [comment]
@tforster no issue on your side I think, GitHub rendered the markdown correct for example. Seems to be an issue in mkdocs.

**Pull request merged**
